[package]
name = "rust-solo-all-db"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

[dev-dependencies]
tempfile = "3.0"

[[bin]]
name = "rustdb"
path = "src/main.rs"