// Example usage of the procedural macros

use rust_solo_all_db_macros::*;
use serde::{Serialize, Deserialize};

// Example 1: Query Builder Derive Macro
#[derive(Debug, Clone, Serialize, Deserialize, QueryBuilder)]
struct User {
    #[primary_key]
    id: String,
    #[indexed]
    name: String,
    #[indexed]
    email: String,
    created_at: u64,
}

impl User {
    pub fn new(id: String, name: String, email: String, created_at: u64) -> Self {
        Self { id, name, email, created_at }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, QueryBuilder)]
struct Product {
    #[primary_key]
    sku: String,
    name: String,
    #[indexed]
    category: String,
    price: f64,
}

impl Product {
    pub fn new(sku: String, name: String, category: String, price: f64) -> Self {
        Self { sku, name, category, price }
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("🚀 Demonstrating Procedural Macros");

    // Example 4: Database Configuration Macro
    let mut db = database! {
        path: "data/macro_example",
        memtable_size: 1000,
        enable_wal: true
    }?;

    // Example 5: Using Generated Query Builder Methods
    let user = User::new(
        "user001".to_string(),
        "Alice Smith".to_string(),
        "alice@example.com".to_string(),
        1642838400, // Unix timestamp
    );

    println!("💾 Saving user: {:?}", user);
    user.save(&mut db)?;

    // Find user by ID (generated method)
    if let Some(found_user) = User::find_by_id(&db, "user001")? {
        println!("🔍 Found user by ID: {:?}", found_user);
    }

    // Example 6: Using Product with Generated Methods
    let product = Product::new(
        "LAPTOP001".to_string(),
        "Gaming Laptop".to_string(),
        "Electronics".to_string(),
        1299.99,
    );

    product.save(&mut db)?;
    println!("💾 Saved product: {:?}", product);

    println!("✅ All procedural macro examples completed successfully!");

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_query_builder_derive() {
        let temp_dir = tempdir().unwrap();
        let config = rust_solo_all_db::engine::LSMConfig {
            memtable_size_limit: 100,
            data_dir: temp_dir.path().join("db"),
            background_compaction: false,
            background_compaction_interval: std::time::Duration::from_secs(1),
            enable_wal: false,
        };
        
        let mut db = rust_solo_all_db::engine::LSMTree::with_config(config).unwrap();
        
        // Test generated methods
        let user = User::new(
            "test001".to_string(),
            "Test User".to_string(),
            "test@example.com".to_string(),
            1642838400,
        );

        // Test save (generated by macro)
        user.save(&mut db).unwrap();

        // Test find_by_id (generated by macro)
        let found = User::find_by_id(&db, "test001").unwrap();
        assert!(found.is_some());
        assert_eq!(found.unwrap().name, "Test User");

        // Test delete (generated by macro)
        let deleted = User::delete_by_id(&mut db, "test001").unwrap();
        assert!(deleted);

        // Verify deletion
        let not_found = User::find_by_id(&db, "test001").unwrap();
        assert!(not_found.is_none());
    }

    #[test]
    fn test_database_macro() {
        let db_result = database! {
            path: "data/test",
            memtable_size: 500,
            enable_wal: false
        };
        
        assert!(db_result.is_ok());
    }
}